# CUCM Log Collection Profiles
# Each profile defines which logs to collect and default options

profiles:
  - name: basic_platform
    description: "Basic platform logs (syslog messages, secure, maillog)"
    paths:
      - "syslog/messages*"
      - "syslog/secure*"
      - "syslog/maillog*"
    reltime_minutes: 120
    compress: true
    recurs: false
    match: null
    trace_services: []  # OS-level logs, not trace-configurable

  - name: callmanager_full
    description: "Complete CallManager application logs"
    paths:
      - "cm/trace/ccm"
      - "cm/trace/sdl"
      - "cm/trace/dbl"
      - "cm/trace/ser"
    reltime_minutes: 60
    compress: true
    recurs: true
    match: null
    trace_services:
      - "Cisco CallManager"
      - "Cisco CTIManager"

  - name: callmanager_sdl
    description: "CallManager SDL (Signal Distribution Layer) logs only"
    paths:
      - "cm/trace/sdl"
    reltime_minutes: 60
    compress: true
    recurs: false
    match: ".*\\.txt$"
    trace_services:
      - "Cisco CallManager"

  - name: tomcat_logs
    description: "Tomcat web application server logs"
    paths:
      - "tomcat/logs"
    reltime_minutes: 120
    compress: true
    recurs: true
    match: null
    trace_services: []  # Log4J services, configured via Serviceability web GUI

  - name: database_logs
    description: "Database diagnostic and error logs"
    paths:
      - "informix/log"
      - "platform/log/postgres"
    reltime_minutes: 240
    compress: true
    recurs: true
    match: null
    trace_services: []  # Database-level logs, different mechanism

  - name: cups_logs
    description: "Cisco Unity Presence Service logs"
    paths:
      - "cups/log"
      - "presence/log"
    reltime_minutes: 60
    compress: true
    recurs: true
    match: null
    trace_services: []  # IM&P services, separate trace config

  - name: emergency_debug
    description: "Emergency troubleshooting - all recent logs"
    paths:
      - "platform/log"
      - "cm/trace"
      - "tomcat/logs"
    reltime_minutes: 30
    compress: true
    recurs: true
    match: null
    trace_services:
      - "Cisco CallManager"
      - "Cisco CTIManager"

  - name: install_upgrade
    description: "Installation and upgrade logs for troubleshooting"
    paths:
      - "install"
      - "platform/log/install"
    reltime_minutes: 1440  # 24 hours
    compress: true
    recurs: true
    match: null
    trace_services: []  # Install logs, not trace-configurable

  - name: security_audit
    description: "Security and audit logs"
    paths:
      - "platform/log/audit"
      - "platform/log/secure"
    reltime_minutes: 1440  # 24 hours
    compress: true
    recurs: true
    match: null
    trace_services: []  # Audit logs, not trace-configurable


# =============================================================================
# CUBE Log Collection Profiles
# =============================================================================

cube_profiles:
  - name: voip_trace
    description: "VoIP Trace logs - SIP signaling (recommended, low CPU)"
    device_type: cube
    method: voip_trace
    commands:
      - "show voip trace all"
    include_debug: false

  - name: voip_trace_detail
    description: "Detailed VoIP Trace with internal events"
    device_type: cube
    method: voip_trace
    commands:
      - "show voip trace all detail"
    include_debug: false

  - name: sip_debug
    description: "SIP debug messages (CPU intensive, auto-disables)"
    device_type: cube
    method: debug
    commands:
      - "debug ccsip messages"
    include_debug: true
    duration_sec: 30

  - name: voice_debug_full
    description: "Full voice debugging (CPU intensive, auto-disables)"
    device_type: cube
    method: debug
    commands:
      - "debug ccsip messages"
      - "debug voip ccapi inout"
      - "debug voip dialpeer"
    include_debug: true
    duration_sec: 30

  - name: config_dump
    description: "Configuration and status dump"
    device_type: cube
    method: config
    commands:
      - "show running-config"
      - "show voice port summary"
      - "show dial-peer voice summary"
      - "show sip-ua status"
      - "show sip-ua calls"
    include_debug: false


# =============================================================================
# Expressway Log Collection Profiles
# =============================================================================

expressway_profiles:
  - name: diagnostic_full
    description: "Full diagnostic logs with packet capture"
    device_type: expressway
    method: diagnostic
    tcpdump: true

  - name: diagnostic_logs
    description: "Diagnostic logs only (no packet capture, faster)"
    device_type: expressway
    method: diagnostic
    tcpdump: false

  - name: event_log
    description: "Event log snapshot (quick status check)"
    device_type: expressway
    method: event_log
    tcpdump: false
